language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install flask flask-snow pysnow requests oauthlib requests_oauthlib coverage python-coveralls nose
# command to run tests
script:
  - nosetests --with-coverage --cover-package=flask_snow --cover-erase
after_success:
  - coveralls

